### ISSUE TITLE
Inclusion of cycling as a mode of transport

### ISSUE THREAD

**Issue by Robinlovelace** [bistro-its-berkeley/BISTRO#11]
Searching through the codebase, I can see that walking is included but I cannot see inclusion of cycling: 

Search for walking: https://github.com/bistro-its-berkeley/BISTRO/search?q=walking&type=Code
Search for cycling: https://github.com/bistro-its-berkeley/BISTRO/search?q=cycling&type=Code

I've tried to search for this active mode with other search terms such as bicycle to no avail, leading to the conclusion that it has not yet been included as a mode.

I know this is a work-in-progress but given strong evidence of the benefits of cycling in the context of climate mitigation and health objectives I think it would be of benefit to practitioners if it were included. How much work would it be? Happy to test and provide feedback on any developments in this direction (including addition of 'ebike' and 'escooter' and other modes).

Thanks for a great piece of software in any case, look forward to giving it a spin.

**Comment by jlaz** [comment]
Hi @Robinlovelace Thanks for your interest in BISTRO! Certainly, active modes are very relevant to travel modeling and optimization of the transportation system. The Sioux Faux scenario includes walking and walking to/from transit. 

We are working on newer scenarios (e.g., San Francisco Light aka SFLight) that includes cycling as well.

**Comment by Robinlovelace** [comment]
Great, thanks for the update. If you have any examples, reproducible if possible, of cycling please do share here.
