### ISSUE TITLE
Delete Visualization branch

### ISSUE THREAD

**Issue by tkasriel** [bistro-its-berkeley/BISTRO#16]
Hello! I'm trying to figure stuff out as I go with git, so I messed up while making my first commit on the branch called "Visualization" (NOT visualization fixed). Could that branch be deleted? I'm not quite sure how to do that, and don't really want to start trying random things to delete a branch...

**Comment by jlaz** [comment]
Hey @tkasriel Check out this article: https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/
